# Generated by Django 2.1.3 on 2018-12-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.DateField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('cgpa', models.IntegerField()),
                ('dob', models.DateField()),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('contact', models.IntegerField()),
                ('batch', models.IntegerField()),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
