# Generated by Django 2.1.3 on 2018-12-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20181203_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='cgpa',
            field=models.FloatField(),
        ),
    ]
