# Generated by Django 2.1.3 on 2018-12-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20181204_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='batch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
