# Generated by Django 2.1.3 on 2018-12-05 05:45

from django.conf import settings
from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0007_studentinfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='owner',
            field=models.ForeignKey(default=1, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[students.validators.validate_section]),
        ),
    ]
