# Generated by Django 2.1.3 on 2018-12-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20181205_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
