# Generated by Django 2.1.3 on 2018-12-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_studentinfo_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='gender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
