# Generated by Django 2.1.3 on 2018-12-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20181211_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
