# Generated by Django 2.1.3 on 2018-12-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20181211_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
