# Generated by Django 2.1.3 on 2018-12-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20181211_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='reg_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
