# Generated by Django 2.1.3 on 2018-12-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20181213_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
