# Generated by Django 2.1.3 on 2018-12-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenurl', '0002_auto_20181211_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlinfo',
            name='original_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
