# Generated by Django 2.1.3 on 2018-12-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_tweetinfo_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetinfo',
            name='total_tweet_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
