# Generated by Django 2.1.3 on 2018-12-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='content',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
