# Generated by Django 2.1.3 on 2018-12-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181214_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloginfo',
            old_name='lat_updated',
            new_name='last_updated',
        ),
    ]
