# Generated by Django 2.1.3 on 2018-12-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181215_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='preview_points',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
