# Generated by Django 2.1.3 on 2018-12-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_bloginfo_preview_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='use_editor',
            field=models.BooleanField(default=False),
        ),
    ]
