# Generated by Django 2.1.3 on 2018-12-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181217_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
