# Generated by Django 2.1.3 on 2018-12-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_commentsinfo_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsinfo',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
