# Generated by Django 2.1.3 on 2018-12-21 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_commentsinfo_is_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
