# Generated by Django 2.1.3 on 2018-12-09 06:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counter', '0002_auto_20181209_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountUpdateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=10, null=True)),
                ('action_count', models.IntegerField(blank=True, null=True)),
                ('date_time', models.DateTimeField(auto_now=True, null=True)),
                ('previous_value', models.IntegerField(blank=True, null=True)),
                ('next_value', models.IntegerField(blank=True, null=True)),
                ('operation_success', models.BooleanField(blank=True, null=True)),
                ('name', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
