# Generated by Django 2.1.3 on 2018-12-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_countupdateinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countupdateinfo',
            name='name',
        ),
        migrations.AddField(
            model_name='countupdateinfo',
            name='counter_r',
            field=models.ForeignKey(default=1, on_delete='CASCADE', to='counter.CountInfo'),
            preserve_default=False,
        ),
    ]
