# Generated by Django 2.1.3 on 2018-12-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181206_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
