# Generated by Django 2.1.3 on 2018-12-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181207_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='activation_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
