# Generated by Django 2.1.3 on 2018-12-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_accountinfo_activation_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
