# Generated by Django 2.1.3 on 2018-12-10 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accountinfo_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
